<?php
/**
 * Created by PhpStorm.
 * User: Алексей
 * Date: 26.05.2019
 * Time: 20:33
 */

class SQLPDO extends ParentSQL
{
    private $dbh;

    public function __construct()
    {
        parent::__construct();
        $options = [
            \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION,
            \PDO::ATTR_DEFAULT_FETCH_MODE => \PDO::FETCH_ASSOC
        ];
        $this->dbh = new PDO("mysql:host=" . DB_HOST . ";dbname=" . DB_NAME. ";charset=utf8", DB_USER, DB_PASS, $options);
    }

    public function insertRow()
    {
        parent::insertRow(); // TODO: Change the autogenerated stub
        foreach($this->values as $oneValue)
        {
            foreach ($oneValue as $key => $value) {
                $field .= $key . ", ";
                $values .= "?, ";
            }
        }
        $fields = substr($field, 0, -2);
        $this->query = "INSERT INTO {$this->table} ({$fields}) VALUES ({$values})";
        foreach
        $sth = $this->dbh->prepare($this->query);
        return $sth;
    }


    /* Выполнение запроса с привязкой PHP-переменных
    $calories = 150;
    $colour = 'red';
    $sth = $dbh->prepare('SELECT name, colour, calories
        FROM fruit
        WHERE calories < ? AND colour = ?');
    $sth->bindParam(1, $calories, PDO::PARAM_INT);
    $sth->bindParam(2, $colour, PDO::PARAM_STR, 12);
    $sth->execute();*/
}